## **RQ3**

> _Em modelos globais para previsão multi-horizonte de poluentes, quando variáveis exógenas (meteorologia + co-poluentes) geram ganho real de desempenho — e esse ganho é explicável por atribuições consistentes e fisicamente plausíveis?_

* Avaliação empírica (não arquitetural) do impacto de exógenas;
* Horizontes de 7, 14 e 30 dias;
* Análise explícita de:
   * quando exógenas ajudam,
   * quando não ajudam,
   * possíveis razões físicas e estatísticas.

## Libraries

In [1]:
import os
os.environ['NIXTLA_ID_AS_COL'] = '1'

import optuna
import itertools
import shutil
import time
import functools
import gc
import requests
import pickle

import pandas as pd
import numpy as np
np.random.seed(1)

import plotly.graph_objects as go
import plotly.express as px
import plotly.subplots
import plotly.io as pio
from graphmodex import plotlymodex
pio.renderers.default = 'notebook'

import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib as mpl

import joblib
import pickle
from IPython.display import clear_output

In [2]:
import neuralforecast
import mlforecast
import statsforecast
import utilsforecast
import coreforecast

from statsforecast import StatsForecast
from statsforecast.models import (
    Naive, SeasonalNaive,
    AutoARIMA, AutoCES, AutoETS, AutoTheta,
)

from mlforecast import MLForecast
import lightgbm as lgb
from sklearn.linear_model import LinearRegression
from mlforecast.lag_transforms import ExpandingMean, RollingMean
from mlforecast.target_transforms import Differences
import xgboost as xgb
from sklearn.ensemble import RandomForestRegressor

from neuralforecast import NeuralForecast
from neuralforecast.models import (
    NBEATS, NHITS, NBEATSx,
    GRU, Informer, LSTM
)
from neuralforecast.losses.pytorch import MSE, SMAPE, MAE

from mlforecast.utils import PredictionIntervals

from pytorch_lightning import Trainer
trainer = Trainer(
    max_steps=4,
    logger=False,
    enable_progress_bar=False,
    enable_model_summary=False
)

import warnings
warnings.filterwarnings("ignore", category=UserWarning, module="optuna")


# ==================================================
# REPRODUCTIBILITY
# ==================================================
import random
import torch

SEED = 1
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)
torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.

### Results Storage

In [3]:
from pathlib import Path

BASE_RESULTS = Path("Results/RQ3")
BASE_RESULTS.mkdir(parents=True, exist_ok=True)

def save_results(df, model_family, pollutant, horizon_label, fold=None):

    out_dir = BASE_RESULTS / model_family
    out_dir.mkdir(parents=True, exist_ok=True)

    if fold is not None:
        fname = f"{pollutant}_{fold}_{horizon_label}.csv"
    else:
        fname = f"{pollutant}_{horizon_label}.csv"

    df.to_csv(out_dir / fname, index=False)

## Data

In [4]:
# ===============================
# DATA
# ===============================
df = pd.read_parquet(r'..\Data\CAMS\processed\eac4_era5_2010_2024_brasil_enhanced.parquet')


# ===============================
# POLLUTANTS
# ===============================
pm2p5 = (
    df
    .copy()
    .rename(columns={
        'pm2p5': 'y',
        'valid_time': 'ds'        
    })
    .query("ds >= '2010-01-01'")
)

go3 = (
    df
    .copy()
    .rename(columns={
        'go3': 'y',
        'valid_time': 'ds'        
    })
    .query("ds >= '2010-01-01'")
)

In [5]:
BASE_COLS = [ "ds", "unique_id", "y"]

O3_F1 = ["no2", "co"]
O3_F2 = ["u10", "v10", "wind_speed", "t2m", "d2m", "RH", "ssrd_flux", "blh"]
O3_F3 = O3_F1 + O3_F2

PM_F1 = ["so2", "no2", "co"]
PM_F2 = ["u10", "v10", "wind_speed", "t2m", "d2m", "RH", "ssrd_flux", "blh"]
PM_F3 = PM_F1 + PM_F2

In [6]:
pollutant_dict = {
    'go3': {
        'f0': {
            'df': go3[BASE_COLS].copy(),
            'exog_cols': []
        },
        'f1': {
            'df': go3[BASE_COLS + O3_F1].copy(),
            'exog_cols': O3_F1
        },
        'f2': {
            'df': go3[BASE_COLS + O3_F2].copy(),
            'exog_cols': O3_F2
        },
        'f3': {
            'df': go3[BASE_COLS + O3_F3].copy(),
            'exog_cols': O3_F3
        },
        'scaler': 1e8
    },

    'pm2p5': {
        'f0': {
            'df': pm2p5[BASE_COLS].copy(),
            'exog_cols': []
        },
        'f1': {
            'df': pm2p5[BASE_COLS + PM_F1].copy(),
            'exog_cols': PM_F1
        },
        'f2': {
            'df': pm2p5[BASE_COLS + PM_F2].copy(),
            'exog_cols': PM_F2
        },
        'f3': {
            'df': pm2p5[BASE_COLS + PM_F3].copy(),
            'exog_cols': PM_F3
        },
        'scaler': 1e9
    }
}

In [7]:
# Função para ajustar pela ordem inversa de grandeza de cada poluente
def adjust_by_inverse_magnitude(df, pollutants):
    for pollutant in pollutants:
        if pollutant in df.columns:
            # Calcular a mediana do poluente
            median_value = df[pollutant].median()
            # Calcular a ordem de grandeza (log base 10 da mediana)
            magnitude = np.floor(np.log10(abs(median_value)))
            # Multiplicar pela inversa da ordem de grandeza (10^(-magnitude))
            df[pollutant] *= 10 ** (-magnitude)
    return df

# Iterar sobre cada poluente no dicionário e ajustar os dados
for pollutant, data in pollutant_dict.items():
    for key, val in data.items():
        # Identificar os poluentes a serem ajustados (so2, no2, co)
        if isinstance(val, dict):
            df = val['df']
            exog_cols = val['exog_cols']
            # Ajustar as colunas de poluentes (se houver)
            df = adjust_by_inverse_magnitude(df, ['so2', 'no2', 'co'])

            # Atualizar o dicionário com o DataFrame ajustado
            pollutant_dict[pollutant][key]['df'] = df

# Resultado: dicionário de poluentes com os DataFrames ajustados

### Setup

In [8]:
# ===============================
# CONFIG
# ===============================
steps_per_day = 8
two_year_steps = 2 * 365 * steps_per_day
target_windows = 30

FREQ = '3h'
SEASON_LENGTH = 8 

experiments_dict = {
    # '1 days': {
    #     'horizon': 8*1,
    #     'step_size': max(8*1, two_year_steps // target_windows),
    #     'windows': target_windows,
    # },
    '30 days': {
        'horizon': 8*30,
        'step_size': 8*30,
        'windows': two_year_steps // (8*30),  # 24
    },
    '14 days': {
        'horizon': 8*14,
        'step_size': max(8*14, two_year_steps // target_windows),
        'windows': target_windows,
    },
    '7 days': {
        'horizon': 8*7,
        'step_size': max(8*7, two_year_steps // target_windows),
        'windows': target_windows,
    },
}

# **Models**

### Neural

In [ ]:
for pollutant_name, pollutant_ in pollutant_dict.items():
    
    scaler = pollutant_['scaler']

    if pollutant_name == 'go3':
        continue
    
    for fk_label in ['f3', 'f2',]:
        
        for horizon_label, experiment_ in experiments_dict.items():
            
            try:
                clear_output(wait=True)
                print(f"Running RQ3 | {pollutant_name} | {fk_label} | {horizon_label}")

                # --------------------------------
                # DATA (copy fresh every iteration)
                # --------------------------------
                df_config = pollutant_[fk_label]['df'].copy()
                exog_cols = pollutant_[fk_label]['exog_cols']

                # Scale target
                df_config['y'] = df_config['y'] * scaler

                # --------------------------------
                # MODELS
                # --------------------------------
                models = [
                    GRU(
                        h=experiment_['horizon'],
                        input_size=14*8,
                        max_steps=1000,
                        learning_rate=1e-3,
                        batch_size=8,
                        windows_batch_size=8,
                        random_seed=SEED,
                        alias='GRU',
                        loss=MAE(),
                        hist_exog_list=exog_cols if exog_cols else None,
                        logger=False,
                    ),
                    # LSTM(
                    #     h=experiment_['horizon'],
                    #     input_size=14*8,
                    #     max_steps=1000,
                    #     learning_rate=1e-3,
                    #     batch_size=8,
                    #     windows_batch_size=8,
                    #     random_seed=SEED,
                    #     alias='LSTM',
                    #     loss=MAE(),
                    #     hist_exog_list=exog_cols if exog_cols else None,
                    #     logger=False,
                    # ),
                    NBEATSx(
                        h=experiment_['horizon'],
                        input_size=14*8,
                        stack_types=["identity", "trend", "seasonality"],
                        n_blocks=[1, 1, 1],
                        mlp_units=3 * [[256, 256]],
                        shared_weights=True,
                        activation='ReLU',
                        max_steps=1000,
                        learning_rate=1e-3,
                        batch_size=8,
                        windows_batch_size=8,
                        random_seed=SEED,
                        alias='NBEATSx-I',
                        hist_exog_list=exog_cols if exog_cols else None,
                        loss=MAE(),
                    ),
                    NBEATSx(
                        h=experiment_['horizon'],
                        input_size=14*8,
                        stack_types=['identity'] * 3,
                        n_blocks=[2, 2, 2],
                        mlp_units=3 * [[256, 256]],
                        shared_weights=False,
                        activation='ReLU',
                        max_steps=1000,
                        learning_rate=1e-3,
                        batch_size=8,
                        windows_batch_size=8,
                        random_seed=SEED,
                        alias='NBEATSx-G',
                        logger=False,
                        hist_exog_list=exog_cols if exog_cols else None,
                        loss=MAE(),
                    ),
                    NHITS(
                        h=experiment_['horizon'],
                        input_size=14*8,
                        n_blocks=[1, 1, 1],
                        mlp_units=3 * [[256, 256]],
                        n_pool_kernel_size=[2, 2, 1],
                        n_freq_downsample=[4, 2, 1],
                        activation='ReLU',
                        dropout_prob_theta=0.1,
                        max_steps=1000,
                        learning_rate=1e-3,
                        batch_size=8,
                        windows_batch_size=8,
                        random_seed=SEED,
                        alias='NHITS',
                        logger=False,
                        hist_exog_list=exog_cols if exog_cols else None,
                        loss=MAE(),
                    ),
                ]

                nf = NeuralForecast(models=models, freq=FREQ)

                # --------------------------------
                # CROSS VALIDATION
                # --------------------------------
                start_time = time.time()

                results_nf = nf.cross_validation(
                    df=df_config,
                    h=experiment_['horizon'],
                    n_windows=experiment_['windows'],
                    step_size=experiment_['step_size'],
                    refit=False,
                )

                end_time = time.time()
                total_time = end_time - start_time

                results_nf['fit_time_seconds'] = total_time

                # --------------------------------
                # SCALE BACK
                # --------------------------------
                for col in ['y', 'GRU', 'LSTM', 'NBEATSx-I', 'NBEATSx-G', 'NHITS']:
                    if col in results_nf.columns:
                        results_nf[col] = results_nf[col] / scaler

                # --------------------------------
                # SAVE
                # --------------------------------
                save_results(
                    results_nf,
                    model_family="dl",
                    pollutant=pollutant_name,
                    horizon_label=horizon_label.replace(" ", ""),
                    fold=fk_label
                )

                # --------------------------------
                # CLEAN MEMORY
                # --------------------------------
                del nf
                del models
                gc.collect()
                torch.cuda.empty_cache()

            except Exception as e:
                print(f"Failed on {pollutant_name} {fk_label} {horizon_label}: {e}")
                continue

In [12]:
os.makedirs("./models_dl", exist_ok=True)

for pollutant_name, pollutant_ in pollutant_dict.items():

    scaler = pollutant_['scaler']

    for fk_label in ['f3',]:
        
        for horizon_label, experiment_ in experiments_dict.items():
            
            try:
                clear_output(wait=True)
                print(f"Running RQ3 | {pollutant_name} | {fk_label} | {horizon_label}")

                # --------------------------------
                # DATA (copy fresh every iteration)
                # --------------------------------
                df_config = pollutant_[fk_label]['df'].copy()
                exog_cols = pollutant_[fk_label]['exog_cols']

                # Scale target
                df_config['y'] = df_config['y'] * scaler

                df_config = df_config.sort_values(['unique_id','ds'])

                # --------------------------------
                # MODELS
                # --------------------------------
                models = [
                    # GRU(
                    #     h=experiment_['horizon'],
                    #     input_size=14*8,
                    #     max_steps=1000,
                    #     learning_rate=1e-3,
                    #     batch_size=8,
                    #     windows_batch_size=8,
                    #     random_seed=SEED,
                    #     alias='GRU',
                    #     loss=MAE(),
                    #     hist_exog_list=exog_cols if exog_cols else None,
                    #     logger=False,
                    # ),
                    # LSTM(
                    #     h=experiment_['horizon'],
                    #     input_size=14*8,
                    #     max_steps=1000,
                    #     learning_rate=1e-3,
                    #     batch_size=8,
                    #     windows_batch_size=8,
                    #     random_seed=SEED,
                    #     alias='LSTM',
                    #     loss=MAE(),
                    #     hist_exog_list=exog_cols if exog_cols else None,
                    #     logger=False,
                    # ),
                    NBEATSx(
                        h=experiment_['horizon'],
                        input_size=14*8,
                        stack_types=["identity", "trend", "seasonality"],
                        n_blocks=[1, 1, 1],
                        mlp_units=3 * [[256, 256]],
                        shared_weights=True,
                        activation='ReLU',
                        max_steps=1000,
                        learning_rate=1e-3,
                        batch_size=8,
                        windows_batch_size=8,
                        random_seed=SEED,
                        alias='NBEATSx-I',
                        hist_exog_list=exog_cols if exog_cols else None,
                        loss=MAE(),
                    ),
                    NBEATSx(
                        h=experiment_['horizon'],
                        input_size=14*8,
                        stack_types=['identity'] * 3,
                        n_blocks=[2, 2, 2],
                        mlp_units=3 * [[256, 256]],
                        shared_weights=True,
                        activation='ReLU',
                        max_steps=1000,
                        learning_rate=1e-3,
                        batch_size=8,
                        windows_batch_size=8,
                        random_seed=SEED,
                        alias='NBEATSx-G',
                        logger=False,
                        hist_exog_list=exog_cols if exog_cols else None,
                        loss=MAE(),
                    ),
                    NHITS(
                        h=experiment_['horizon'],
                        input_size=14*8,
                        n_blocks=[1, 1, 1],
                        mlp_units=3 * [[256, 256]],
                        n_pool_kernel_size=[2, 2, 1],
                        n_freq_downsample=[4, 2, 1],
                        activation='ReLU',
                        dropout_prob_theta=0.1,
                        max_steps=1000,
                        learning_rate=1e-3,
                        batch_size=8,
                        windows_batch_size=8,
                        random_seed=SEED,
                        alias='NHITS',
                        logger=False,
                        hist_exog_list=exog_cols if exog_cols else None,
                        loss=MAE(),
                    ),
                    # NHITS(
                    #     h=experiment_['horizon'],
                    #     input_size=14*8,
                    #     n_blocks=[1, 1, 1],
                    #     mlp_units=3 * [[256, 256]],
                    #     n_pool_kernel_size=[2, 2, 1],
                    #     n_freq_downsample=[4, 2, 1],
                    #     activation='ReLU',
                    #     dropout_prob_theta=0.1,
                    #     max_steps=1000,
                    #     learning_rate=1e-3,
                    #     batch_size=8,
                    #     windows_batch_size=8,
                    #     random_seed=SEED,
                    #     alias='NHITS-MSE',
                    #     logger=False,
                    #     hist_exog_list=exog_cols if exog_cols else None,
                    #     loss=MSE(),
                    # ),
                ]

                nf = NeuralForecast(models=models, freq=FREQ, local_static_scaler_type="standard")

                # --------------------------------
                # FIT
                # --------------------------------
                start_time = time.time()

                nf.fit(df_config.query("ds <= '2022-12-31'"))

                # --------------------------------
                # SAVE MODEL
                # --------------------------------
                model_path = rf"./models_dl/{pollutant_name}_{fk_label}_{horizon_label.replace(' ','')}.pkl"

                with open(model_path, "wb") as f:
                    pickle.dump(nf, f)

                # --------------------------------
                # CUT-OFFS (same CV logic)
                # --------------------------------
                h = experiment_['horizon']
                step_size = experiment_['step_size']
                n_windows = experiment_['windows']

                rq1_cutoffs = pd.read_csv(
                    rf'.\Results\RQ1\ml\go3_{horizon_label.replace(" ","")}.csv'
                )['cutoff'].unique()

                rq1_cutoffs = pd.to_datetime(rq1_cutoffs)
                rq1_cutoffs = sorted(rq1_cutoffs)

                cutoffs = rq1_cutoffs[:n_windows]

                results_list = []

                freq_offset = pd.tseries.frequencies.to_offset(FREQ)

                # --------------------------------
                # LOOP CUT-OFFS
                # --------------------------------
                for cutoff in cutoffs:

                    hist_df = df_config[df_config['ds'] <= cutoff]

                    preds = nf.predict(
                        df=hist_df,
                        h=h
                    )

                    start_forecast = cutoff + freq_offset
                    end_forecast = cutoff + h * freq_offset

                    preds = preds[ 
                        (preds['ds'] >= start_forecast) &
                        (preds['ds'] <= end_forecast)
                    ]

                    real = df_config[
                        (df_config['ds'] >= start_forecast) & 
                        (df_config['ds'] <= end_forecast)
                    ][['unique_id', 'ds', 'y']]

                    merged = preds.merge(real, on=['unique_id','ds'], how='left')

                    merged['cutoff'] = cutoff
                    merged['fold'] = fk_label

                    results_list.append(merged)

                results_nf = pd.concat(results_list)

                end_time = time.time()
                total_time = end_time - start_time

                results_nf['fit_time_seconds'] = total_time

                # --------------------------------
                # SCALE BACK (Desescalonamento)
                # --------------------------------
                for col in ['y', 'GRU', 'LSTM', 'NBEATSx-I', 'NBEATSx-G', 'NHITS', 'Informer']:
                    if col in results_nf.columns:
                        results_nf[col] = results_nf[col] / scaler

                # --------------------------------
                # SAVE RESULTS
                # --------------------------------
                save_results(
                    results_nf,
                    model_family="neural",
                    pollutant=pollutant_name,
                    horizon_label=horizon_label.replace(" ", ""),
                    fold=fk_label
                )

                # --------------------------------
                # CLEAN MEMORY
                # --------------------------------
                del nf
                del models
                gc.collect()
                torch.cuda.empty_cache()

            except Exception as e:
                print(f"Failed on {pollutant_name} {fk_label} {horizon_label}: {e}")
                continue

Running RQ3 | pm2p5 | f3 | 7 days

Seed set to 1
Seed set to 1
Seed set to 1
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name         | Type          | Params | Mode  | FLOPs
---------------------------------------------------------------
0 | loss         | MAE           | 0      | train | 0
1 | padder_train | ConstantPad1d | 0      | train | 0
2 | scaler       | TemporalNorm  | 0      | train | 0
3 | blocks       | ModuleList    | 1.7 M  | train | 0
---------------------------------------------------------------
1.7 M     Trainable params
19.0 K    Non-trainable params
1.7 M     Total params
6.981     Total estimated model params size (MB)
31        Modules in train mode
0         Modules in eval mode
0         Total Flops

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_steps=1000` reached.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name         | Type          | Params | Mode  | FLOPs
---------------------------------------------------------------
0 | loss         | MAE           | 0      | train | 0
1 | padder_train | ConstantPad1d | 0      | train | 0
2 | scaler       | TemporalNorm  | 0      | train | 0
3 | blocks       | ModuleList    | 1.8 M  | train | 0
---------------------------------------------------------------
1.8 M     Trainable params
0         Non-trainable params
1.8 M     Total params
7.018     Total estimated model params size (MB)
31        Modules in train mode
0         Modules in eval mode
0         Total Flops

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_steps=1000` reached.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name         | Type          | Params | Mode  | FLOPs
---------------------------------------------------------------
0 | loss         | MAE           | 0      | train | 0
1 | padder_train | ConstantPad1d | 0      | train | 0
2 | scaler       | TemporalNorm  | 0      | train | 0
3 | blocks       | ModuleList    | 1.4 M  | train | 0
---------------------------------------------------------------
1.4 M     Trainable params
0         Non-trainable params
1.4 M     Total params
5.570     Total estimated model params size (MB)
43        Modules in train mode
0         Modules in eval mode
0         Total Flops

Sanity Checking: |          | 0/? [00:00<?, ?it/s]

Training: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

Validation: |          | 0/? [00:00<?, ?it/s]

`Trainer.fit` stopped: `max_steps=1000` reached.
GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

In [ ]:
pollutants = ['pm2p5']
folds = ['f3']  # f0 has no exog, skip
horizons = ['7days', '14days', '30days']
explainers = [
    'IntegratedGradients',
    # 'ShapleyValueSampling',
    # 'Lime',
    # 'KernelShap',
    # 'InputXGradient',
]

os.makedirs("./models/explain", exist_ok=True)

for pollutant in pollutants:
    for fold in folds:
        for horizon in horizons:

            model_path = rf"./models/{pollutant}_{fold}_{horizon}.pkl"

            if not os.path.exists(model_path):
                print(f"Model not found: {model_path}, skipping.")
                continue

            try:
                with open(model_path, "rb") as f:
                    model = pickle.load(f)
            except Exception as e:
                print(f"Failed to load {model_path}: {e}")
                continue

            for explainer_name in explainers:
                try:
                    print(f"Explaining | {pollutant} | {fold} | {horizon} | {explainer_name}")

                    rnn_aliases = ['LSTM', 'GRU', 'RNN', 'DeepAR']  # adjust to your model names
                    model.models = [m for m in model.models if m.alias not in rnn_aliases]

                    preds_df, explanations = model.explain(explainer=explainer_name)

                    # Save predictions
                    preds_path = rf"./models/explain/{pollutant}_{fold}_{horizon}_{explainer_name}_preds.csv"
                    preds_df.to_csv(preds_path, index=False)

                    # Save explanations (dict of dicts with tensors)
                    expl_path = rf"./models/explain/{pollutant}_{fold}_{horizon}_{explainer_name}_explanations.pkl"
                    with open(expl_path, "wb") as f:
                        pickle.dump(explanations, f)

                    print(f"  Saved: {preds_path}")
                    print(f"  Saved: {expl_path}")

                except Exception as e:
                    print(f"  Failed {explainer_name} on {pollutant}_{fold}_{horizon}: {e}")
                    continue

            # Clean memory after each model
            del model
            gc.collect()
            torch.cuda.empty_cache()

Explaining | pm2p5 | f3 | 7days | IntegratedGradients

d:\Gugu\Masters\.venv\Lib\site-packages\neuralforecast\core.py:1049: UserWarning:

This function is beta and subject to change.

Using stored dataset.

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

  Saved: ./models/explain/pm2p5_f3_7days_IntegratedGradients_preds.csv
  Saved: ./models/explain/pm2p5_f3_7days_IntegratedGradients_explanations.pkl
Explaining | pm2p5 | f3 | 14days | IntegratedGradients
Using stored dataset.

d:\Gugu\Masters\.venv\Lib\site-packages\neuralforecast\core.py:1049: UserWarning:

This function is beta and subject to change.

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

  Saved: ./models/explain/pm2p5_f3_14days_IntegratedGradients_preds.csv
  Saved: ./models/explain/pm2p5_f3_14days_IntegratedGradients_explanations.pkl
Explaining | pm2p5 | f3 | 30days | IntegratedGradients
Using stored dataset.

d:\Gugu\Masters\.venv\Lib\site-packages\neuralforecast\core.py:1049: UserWarning:

This function is beta and subject to change.

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

GPU available: True (cuda), used: True
TPU available: False, using: 0 TPU cores
💡 Tip: For seamless cloud logging and experiment tracking, try installing [litlogger](https://pypi.org/project/litlogger/) to enable LitLogger, which logs metrics and artifacts automatically to the Lightning Experiments platform.
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

Predicting: |          | 0/? [00:00<?, ?it/s]

  Saved: ./models/explain/pm2p5_f3_30days_IntegratedGradients_preds.csv
  Saved: ./models/explain/pm2p5_f3_30days_IntegratedGradients_explanations.pkl

:

### Machine Learners

In [ ]:
for pollutant_name, pollutant_ in pollutant_dict.items():
    
    scaler = pollutant_['scaler']
    
    for fk_label in ['f3', 'f2', 'f1']:
        
        for horizon_label, experiment_ in experiments_dict.items():
            
            try:
                clear_output(wait=True)
                print(f"Running RQ3-ML | {pollutant_name} | {fk_label} | {horizon_label}")

                # --------------------------------
                # DATA (copy fresh every iteration)
                # --------------------------------
                df_config = pollutant_[fk_label]['df']
                df_config = df_config.sort_values(['unique_id', 'ds'])
                
                # --------------------------------
                # MODEL (LightGBM only)
                # --------------------------------
                lgb_model = lgb.LGBMRegressor(
                    n_estimators=500,
                    learning_rate=0.05,
                    num_leaves=31,
                    subsample=0.8,
                    colsample_bytree=0.8,
                    random_state=SEED,
                    n_jobs=10,
                )

                linreg_model = LinearRegression(
                    n_jobs=10 
                )

                # --------------------------------
                # MLForecast
                # --------------------------------
                mlf = MLForecast(
                    models={'LightGBM': lgb_model, 'LinearRegression': linreg_model},
                    freq=FREQ,
                    lags=[1, 2, 4, 8, 16, 24, 56, 112],
                    lag_transforms={
                        8:  [RollingMean(window_size=8), ExpandingMean()],
                        56: [RollingMean(window_size=56)],
                    },
                    date_features=[
                        'hour',
                        'dayofweek',
                        'month',
                        'dayofyear',
                    ],
                )

                # --------------------------------
                # CROSS VALIDATION
                # --------------------------------
                start_time = time.time()

                results_ml = mlf.cross_validation(
                    df=df_config,
                    h=experiment_['horizon'],
                    n_windows=experiment_['windows'],
                    step_size=experiment_['step_size'],
                    refit=False,
                    static_features=[],   
                )

                end_time = time.time()
                total_time = end_time - start_time

                results_ml['fit_time_seconds'] = total_time

                # --------------------------------
                # SAVE
                # --------------------------------
                save_results(
                    results_ml,
                    model_family="ml",
                    pollutant=pollutant_name,
                    horizon_label=horizon_label.replace(" ", ""),
                    fold=fk_label
                )

                # --------------------------------
                # CLEAN MEMORY
                # --------------------------------
                del mlf
                del linreg_model
                del lgb_model
                gc.collect()

            except Exception as e:
                print(f"Failed on {pollutant_name} {fk_label} {horizon_label}: {e}")
                continue

In [ ]:
# Criar diretório para salvar os modelos
os.makedirs("./models", exist_ok=True)

# Loop sobre os poluentes
for pollutant_name, pollutant_ in pollutant_dict.items():
    
    scaler = pollutant_['scaler']
    
    for fk_label in ['f3', 'f2', 'f1', 'f0']:  # Ou adicione 'f0' conforme necessário
        
        for horizon_label, experiment_ in experiments_dict.items():

            try:
                
                clear_output(wait=True)
                print(f"Running RQ3-ML | {pollutant_name} | {fk_label} | {horizon_label}")

                # --------------------------------
                # Dados (copia a cada iteração)
                # --------------------------------
                df_config = pollutant_[fk_label]['df'].copy()
                df_config = df_config.sort_values(['unique_id', 'ds'])

                # Before fitting, shift exogenous columns by h steps
                exog_cols = pollutant_[fk_label]['exog_cols']

                if exog_cols:
                    for col in exog_cols:
                        df_config[col] = df_config.groupby('unique_id')[col].shift(experiment_['horizon'])
                    df_config = df_config.dropna(subset=exog_cols)
                
                # --------------------------------
                # Modelos
                # --------------------------------
                lgb_model = lgb.LGBMRegressor(
                    n_estimators=500,
                    learning_rate=0.05,
                    num_leaves=31,
                    subsample=0.8,
                    colsample_bytree=0.8,
                    random_state=SEED,
                    n_jobs=10,
                )

                linreg_model = LinearRegression(
                    n_jobs=10
                )

                # --------------------------------
                # MLForecast
                # --------------------------------
                mlf = MLForecast(
                    models={'LightGBM': lgb_model, 'LinearRegression': linreg_model},
                    freq=FREQ,
                    lags=[1, 2, 4, 8, 16, 24, 56, 112],
                    lag_transforms={ 
                        8: [RollingMean(window_size=8), ExpandingMean()],
                        56: [RollingMean(window_size=56)],
                    },
                    date_features=[
                        'hour',
                        'dayofweek',
                        'month',
                        'dayofyear',
                    ],
                )

                # --------------------------------
                # Fit manual (sem cross-validation)
                # --------------------------------
                start_time = time.time()

                # Ajustando o modelo aos dados
                mlf.fit(df_config, static_features=[])

                # --------------------------------
                # Salvando o modelo
                # --------------------------------
                model_path = rf"./models/{pollutant_name}_{fk_label}_{horizon_label.replace(' ','')}.pkl"

                with open(model_path, "wb") as f:
                    pickle.dump(mlf, f)

                # --------------------------------
                # Cortes para o CV
                # --------------------------------
                h = experiment_['horizon']
                step_size = experiment_['step_size']
                n_windows = experiment_['windows']

                rq1_cutoffs = pd.read_csv(
                    rf'.\Results\RQ1\ml\go3_{horizon_label.replace(" ","")}.csv'
                )['cutoff'].unique()

                rq1_cutoffs = pd.to_datetime(rq1_cutoffs)
                rq1_cutoffs = sorted(rq1_cutoffs)

                cutoffs = rq1_cutoffs[:n_windows]

                results_list = []
                freq_offset = pd.tseries.frequencies.to_offset(FREQ)

                # --------------------------------
                # Loop para os cortes (Cutoffs)
                # --------------------------------
                for cutoff in cutoffs:

                    hist_df = df_config[df_config['ds'] <= cutoff]

                    if exog_cols:
                        future_exog = df_config[
                            (df_config['ds'] > cutoff) &
                            (df_config['ds'] <= cutoff + h * freq_offset)
                        ][['unique_id', 'ds'] + exog_cols]
                        preds = mlf.predict(new_df=hist_df, h=h, X_df=future_exog)
                    else:
                        preds = mlf.predict(new_df=hist_df, h=h)

                    start_forecast = cutoff + freq_offset
                    end_forecast = cutoff + h * freq_offset

                    preds = preds[
                        (preds['ds'] >= start_forecast) &
                        (preds['ds'] <= end_forecast)
                    ]

                    real = df_config[
                        (df_config['ds'] >= start_forecast) &
                        (df_config['ds'] <= end_forecast)
                    ][['unique_id', 'ds', 'y']]

                    merged = preds.merge(real, on=['unique_id','ds'], how='left')

                    merged['cutoff'] = cutoff
                    merged['fold'] = fk_label

                    results_list.append(merged)

                results_ml = pd.concat(results_list)

                # Calculando o tempo total
                end_time = time.time()
                total_time = end_time - start_time

                results_ml['fit_time_seconds'] = total_time

                # --------------------------------
                # Salvando os resultados
                # --------------------------------
                save_results(
                    results_ml,
                    model_family="ml_",
                    pollutant=pollutant_name,
                    horizon_label=horizon_label.replace(" ", ""),
                    fold=fk_label
                )

                # --------------------------------
                # Limpando a memória
                # --------------------------------
                del mlf
                del linreg_model
                del lgb_model
                gc.collect()

                # Limpeza extra de memória
                torch.cuda.empty_cache()

            except Exception as e:
                print(f"Failed on {pollutant_name} {fk_label} {horizon_label}: {e}")
                continue

## Merge

In [10]:
BASE_RESULTS = Path(r"C:\Users\gustavo.filho\Documents\Python\Masters_New\Masters 26\Results\RQ3")

FULL_DIR = BASE_RESULTS / "full"
FULL_DIR.mkdir(parents=True, exist_ok=True)

families = ["ml", "dl"]
pollutants = ["go3", "pm2p5"]
folds = ["f0", "f1", "f2", "f3"]
horizons = ["7days", "14days", "30days"]


def build_full_results(pollutant, fold, horizon):

    dfs = []

    for family in families:

        fpath = BASE_RESULTS / family / f"{pollutant}_{fold}_{horizon}.csv"

        if fpath.exists():

            df = pd.read_csv(fpath)

            if "fit_time_seconds" in df.columns:
                df = df.drop(columns=["fit_time_seconds"])

            dfs.append(df)

        else:
            print(f"⚠️ Missing: {fpath}")

    if not dfs:
        return None

    # ordenar igualmente (sem fold)
    for i in range(len(dfs)):
        dfs[i] = dfs[i].sort_values(
            ["unique_id", "ds", "cutoff"]
        ).reset_index(drop=True)

    base = dfs[0][["unique_id", "ds", "cutoff", "y"]].copy()

    for df in dfs:

        model_cols = [
            c for c in df.columns
            if c not in ["unique_id", "ds", "cutoff", "y"]
        ]

        base = pd.concat(
            [base, df[model_cols]],
            axis=1
        )

    return base


for pollutant in pollutants:

    for fold in folds:

        for horizon in horizons:

            print(f"Building FULL | {pollutant} | {fold} | {horizon}")

            df_full = build_full_results(
                pollutant=pollutant,
                fold=fold,
                horizon=horizon
            )

            if df_full is None:
                continue

            df_full.to_csv(
                FULL_DIR / f"{pollutant}_{fold}_{horizon}.csv",
                index=False
            )

Building FULL | go3 | f0 | 7days
Building FULL | go3 | f0 | 14days
Building FULL | go3 | f0 | 30days
Building FULL | go3 | f1 | 7days
Building FULL | go3 | f1 | 14days
Building FULL | go3 | f1 | 30days
Building FULL | go3 | f2 | 7days
Building FULL | go3 | f2 | 14days
Building FULL | go3 | f2 | 30days
Building FULL | go3 | f3 | 7days
Building FULL | go3 | f3 | 14days
Building FULL | go3 | f3 | 30days
Building FULL | pm2p5 | f0 | 7days
Building FULL | pm2p5 | f0 | 14days
Building FULL | pm2p5 | f0 | 30days
Building FULL | pm2p5 | f1 | 7days
Building FULL | pm2p5 | f1 | 14days
Building FULL | pm2p5 | f1 | 30days
Building FULL | pm2p5 | f2 | 7days
Building FULL | pm2p5 | f2 | 14days
Building FULL | pm2p5 | f2 | 30days
Building FULL | pm2p5 | f3 | 7days
Building FULL | pm2p5 | f3 | 14days
Building FULL | pm2p5 | f3 | 30days

## **Estatísticas**

In [42]:
# ==================================================
# METRICS
# ==================================================

def mae(y, yhat):
    return np.mean(np.abs(y - yhat))

def mse(y, yhat):
    return np.mean((y - yhat) ** 2)

def rmse(y, yhat):
    return np.sqrt(mse(y, yhat))

def smape(y, yhat):
    denom = (np.abs(y) + np.abs(yhat)) / 2
    mask = denom != 0
    if mask.sum() == 0:
        return np.nan
    return np.mean(np.abs(y[mask] - yhat[mask]) / denom[mask])

def mae_conditional(y, yhat, threshold):
    mask = y >= threshold
    if mask.sum() == 0:
        return np.nan
    return np.mean(np.abs(y[mask] - yhat[mask]))

def bias_conditional(y, yhat, threshold):
    mask = y >= threshold
    if mask.sum() == 0:
        return np.nan
    return np.mean(yhat[mask] - y[mask])

def skill_score(model_err, baseline_err):
    if baseline_err == 0 or np.isnan(baseline_err):
        return np.nan
    return 1 - model_err / baseline_err


# ΔMAE metric
def delta_mae(mae_f0, mae_fk):
    if mae_f0 == 0 or np.isnan(mae_f0):
        return np.nan
    return (mae_f0 - mae_fk) / mae_f0


def extreme_event_metrics(y, yhat, threshold):

    y_event = y >= threshold
    yhat_event = yhat >= threshold

    tp = np.sum(y_event & yhat_event)
    fp = np.sum(~y_event & yhat_event)
    fn = np.sum(y_event & ~yhat_event)

    precision = tp / (tp + fp) if (tp + fp) > 0 else np.nan
    recall = tp / (tp + fn) if (tp + fn) > 0 else np.nan

    if precision > 0 and recall > 0:
        f1 = 2 * precision * recall / (precision + recall)
    else:
        f1 = np.nan

    return precision, recall, f1


# ==================================================
# CONFIG
# ==================================================

RQ3_BASE = Path("Results/RQ3/full")

pollutants = ["go3", "pm2p5"]
horizons = ["7days", "14days", "30days"]

records = []

# ==================================================
# LOOP
# ==================================================

for pollutant in pollutants:

    for horizon in horizons:

        base_file = RQ3_BASE / f"{pollutant}_f0_{horizon}.csv"

        if not base_file.exists():
            print(f"Missing baseline {base_file}")
            continue

        df_base = pd.read_csv(base_file)

        df_base["ds"] = pd.to_datetime(df_base["ds"])
        df_base["cutoff"] = pd.to_datetime(df_base["cutoff"])

        model_cols = [
            c for c in df_base.columns
            if c not in ["unique_id", "ds", "cutoff", "y"]
        ]

        for fold in ["f0", "f1", "f2", "f3"]:

            file = RQ3_BASE / f"{pollutant}_{fold}_{horizon}.csv"

            if not file.exists():
                print(f"Missing {file}")
                continue

            print(f"Evaluating | {pollutant} | {fold} | {horizon}")

            df = pd.read_csv(file)

            df["ds"] = pd.to_datetime(df["ds"])
            df["cutoff"] = pd.to_datetime(df["cutoff"])

            df = df.merge(
                df_base.drop(columns=["y"]),
                on=["unique_id", "ds", "cutoff"],
                suffixes=("", "_BASE")
            )

            for (uid, cutoff), df_fold in df.groupby(["unique_id", "cutoff"]):

                y = df_fold["y"].values

                if len(y) == 0:
                    continue

                p95 = np.percentile(y, 95)

                for model in model_cols:

                    base_col = model + "_BASE"

                    if base_col not in df_fold.columns:
                        continue

                    yhat = df_fold[model].values
                    y_base = df_fold[base_col].values

                    # baseline LinearRegression
                    if "LinearRegression" in df_fold.columns:
                        y_lr = df_fold["LinearRegression"].values
                    else:
                        y_lr = None

                    mask = (~np.isnan(yhat)) & (~np.isnan(y_base))

                    if y_lr is not None:
                        mask = mask & (~np.isnan(y_lr))

                    if mask.sum() == 0:
                        continue

                    y_valid = y[mask]
                    yhat_valid = yhat[mask]
                    ybase_valid = y_base[mask]

                    mae_model = mae(y_valid, yhat_valid)
                    rmse_model = rmse(y_valid, yhat_valid)
                    smape_model = smape(y_valid, yhat_valid)

                    mae_base = mae(y_valid, ybase_valid)
                    rmse_base = rmse(y_valid, ybase_valid)
                    smape_base = smape(y_valid, ybase_valid)

                    # ΔMAE calculation
                    delta_mae_val = delta_mae(mae_base, mae_model)

                    mae_p95 = mae_conditional(y_valid, yhat_valid, p95)
                    mae_base_p95 = mae_conditional(y_valid, ybase_valid, p95)

                    skill_mae = skill_score(mae_model, mae_base)
                    skill_rmse = skill_score(rmse_model, rmse_base)
                    skill_smape = skill_score(smape_model, smape_base)
                    skill_p95 = skill_score(mae_p95, mae_base_p95)

                    bias_p95 = bias_conditional(y_valid, yhat_valid, p95)

                    precision, recall, f1 = extreme_event_metrics(
                        y_valid, yhat_valid, p95
                    )

                    # ==================================
                    # BASELINE LinearRegression
                    # ==================================

                    if y_lr is not None:

                        ylr_valid = y_lr[mask]

                        mae_lr = mae(y_valid, ylr_valid)
                        rmse_lr = rmse(y_valid, ylr_valid)
                        smape_lr = smape(y_valid, ylr_valid)

                        mae_lr_p95 = mae_conditional(y_valid, ylr_valid, p95)

                        skill_mae_lr = skill_score(mae_model, mae_lr)
                        skill_rmse_lr = skill_score(rmse_model, rmse_lr)
                        skill_smape_lr = skill_score(smape_model, smape_lr)
                        skill_p95_lr = skill_score(mae_p95, mae_lr_p95)

                    else:

                        skill_mae_lr = np.nan
                        skill_rmse_lr = np.nan
                        skill_smape_lr = np.nan
                        skill_p95_lr = np.nan

                    records.append({

                        "pollutant": pollutant,
                        "fold": fold,
                        "horizon": horizon,
                        "unique_id": uid,
                        "cutoff": cutoff,
                        "model": model,

                        "MAE": mae_model,
                        "RMSE": rmse_model,
                        "sMAPE": smape_model,

                        "Delta_MAE": delta_mae_val,

                        "MAE_p95": mae_p95,

                        "Skill_MAE": skill_mae,
                        "Skill_RMSE": skill_rmse,
                        "Skill_sMAPE": skill_smape,
                        "Skill_p95": skill_p95,

                        "Skill_MAE_LR": skill_mae_lr,
                        "Skill_RMSE_LR": skill_rmse_lr,
                        "Skill_sMAPE_LR": skill_smape_lr,
                        "Skill_p95_LR": skill_p95_lr,

                        "Bias_p95": bias_p95,
                        "Precision_p95": precision,
                        "Recall_p95": recall,
                        "F1_p95": f1
                    })

# ==================================================
# SAVE
# ==================================================

metrics_df = pd.DataFrame(records)

metrics_df.to_csv(
    "Results/RQ3/metrics.csv",
    index=False
)

print("Done.")

Evaluating | go3 | f0 | 7days
Evaluating | go3 | f1 | 7days
Evaluating | go3 | f2 | 7days
Evaluating | go3 | f3 | 7days
Evaluating | go3 | f0 | 14days
Evaluating | go3 | f1 | 14days
Evaluating | go3 | f2 | 14days
Evaluating | go3 | f3 | 14days
Evaluating | go3 | f0 | 30days
Evaluating | go3 | f1 | 30days
Evaluating | go3 | f2 | 30days
Evaluating | go3 | f3 | 30days
Evaluating | pm2p5 | f0 | 7days
Evaluating | pm2p5 | f1 | 7days
Evaluating | pm2p5 | f2 | 7days
Evaluating | pm2p5 | f3 | 7days
Evaluating | pm2p5 | f0 | 14days
Evaluating | pm2p5 | f1 | 14days
Evaluating | pm2p5 | f2 | 14days
Evaluating | pm2p5 | f3 | 14days
Evaluating | pm2p5 | f0 | 30days
Evaluating | pm2p5 | f1 | 30days
Evaluating | pm2p5 | f2 | 30days
Evaluating | pm2p5 | f3 | 30days
Done.

# Linear Coefs

### Not Scaled

In [44]:
all_coefs = []

for pollutant_name, pollutant_ in pollutant_dict.items():
    
    scaler = pollutant_['scaler']
    
    for fk_label in ['f3', 'f2', 'f1']:
        
        for horizon_label, experiment_ in experiments_dict.items():
            
            try:
                clear_output(wait=True)
                print(f"Running RQ3-ML | {pollutant_name} | {fk_label} | {horizon_label}")

                # --------------------------------
                # DATA (copy fresh every iteration)
                # --------------------------------
                df_config = pollutant_[fk_label]['df']
                df_config = (
                    df_config
                    .sort_values(['unique_id', 'ds'])
                    .query("ds <= '2022-12-31'")
                )
                
                # --------------------------------
                # MODEL
                # --------------------------------
                linreg_model = LinearRegression(
                    n_jobs=-1
                )

                # --------------------------------
                # MLForecast
                # --------------------------------
                mlf = MLForecast(
                    models={'LinearRegression': linreg_model},
                    freq=FREQ,
                    lags=[1, 2, 4, 8, 16, 24, 56, 112],
                    lag_transforms={
                        8:  [RollingMean(window_size=8), ExpandingMean()],
                        56: [RollingMean(window_size=56)],
                    },
                    date_features=[
                        'hour',
                        'dayofweek',
                        'month',
                        'dayofyear',
                    ],
                )

                # --------------------------------
                # FIT
                # --------------------------------
                mlf.fit(
                    df=df_config,
                    static_features=[]
                )

                # --------------------------------
                # EXTRACT COEFFICIENTS
                # --------------------------------
                model = mlf.models_['LinearRegression']
                features = mlf.ts.features_order_

                coef_df = pd.DataFrame({
                    "feature": features,
                    "coefficient": model.coef_,
                    "pollutant": pollutant_name,
                    "config": fk_label,
                    "horizon": horizon_label
                })

                all_coefs.append(coef_df)

                # --------------------------------
                # CLEAN MEMORY
                # --------------------------------
                del mlf
                del linreg_model
                gc.collect()

            except Exception as e:
                print(f"Failed on {pollutant_name} {fk_label} {horizon_label}: {e}")
                continue


# --------------------------------
# FINAL DATAFRAME
# --------------------------------
coef_df_all = pd.concat(all_coefs, ignore_index=True)

print("Shape:", coef_df_all.shape)
coef_df_all.head()

Running RQ3-ML | pm2p5 | f1 | 7 days
Shape: (396, 5)

      feature   coefficient pollutant config  horizon
0         no2  9.788687e-20       go3     f3  30 days
1          co -1.486658e-15       go3     f3  30 days
2         u10 -7.517060e-10       go3     f3  30 days
3         v10  5.541142e-10       go3     f3  30 days
4  wind_speed  1.429794e-09       go3     f3  30 days

### Scaled

In [14]:
from sklearn.preprocessing import StandardScaler

all_coefs = []

for pollutant_name, pollutant_ in pollutant_dict.items():
    
    scaler = StandardScaler()
    
    for fk_label in ['f3', 'f2', 'f1']:
        
        for horizon_label, experiment_ in experiments_dict.items():
            
            try:
                clear_output(wait=True)
                print(f"Running RQ3-ML | {pollutant_name} | {fk_label} | {horizon_label}")

                df_config = pollutant_[fk_label]['df']
                df_config = (
                    df_config
                    .sort_values(['unique_id', 'ds'])
                    .query("ds <= '2022-12-31'")
                )

                df_config = df_config.copy()

                # escala o target
                df_config['y'] = scaler.fit_transform(df_config[['y']])

                from sklearn.pipeline import Pipeline
                from sklearn.preprocessing import StandardScaler

                linreg_model = Pipeline([
                    ("scaler", StandardScaler()),
                    ("model", LinearRegression())
                ])

                mlf = MLForecast(
                    models={'LinearRegression': linreg_model},
                    freq=FREQ,
                    lags=[1, 2, 4, 8, 16, 24, 56, 112],
                    lag_transforms={
                        8:  [RollingMean(window_size=8), ExpandingMean()],
                        56: [RollingMean(window_size=56)],
                    },
                    date_features=[
                        'hour',
                        'dayofweek',
                        'month',
                        'dayofyear',
                    ],
                )

                mlf.fit(df=df_config, static_features=[])

                model = mlf.models_['LinearRegression'].named_steps['model']
                features = mlf.ts.features_order_

                coef_df = pd.DataFrame({
                    "feature": features,
                    "coefficient": model.coef_,
                    "pollutant": pollutant_name,
                    "config": fk_label,
                    "horizon": horizon_label
                })

                all_coefs.append(coef_df)

                del mlf
                del linreg_model
                gc.collect()

            except Exception as e:
                print(f"Failed on {pollutant_name} {fk_label} {horizon_label}: {e}")
                continue

coef_df_all = pd.concat(all_coefs, ignore_index=True)

print("Shape:", coef_df_all.shape)
coef_df_all.head()

Running RQ3-ML | pm2p5 | f1 | 7 days
Shape: (396, 5)

      feature  coefficient pollutant config  horizon
0         no2    -0.092083       go3     f3  30 days
1          co     0.029261       go3     f3  30 days
2         u10    -0.046739       go3     f3  30 days
3         v10     0.010401       go3     f3  30 days
4  wind_speed     0.062467       go3     f3  30 days

In [15]:
coef_df_all.to_csv(r'lr_coefs_scaled.csv', index=False)

# Feature Importance